#!/usr/bin/env bash
# Installing nginx and make things

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx strat
