#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
redic="https://www.youtube.com/watch?v=QH2-TGUlwu4"
to="/etc/nginx/sites-available/default"
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me ""${redic}"" permanent;' $to
service nginx start
