#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a add_header X-served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
service nginx start
