#!/usr/bin/env bash
#Load Balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "
frontend http_front
	bind *:80
	mode http
	default_backend http_back
backend http_back
	balance roundrobin
	server 1805-web-01 35.237.92.39:80 check
	server 1805-web-02 35.231.86.111:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
