#!/usr/bin/env bash
#display numbers from 1 to 100 with fizz buzz

for a in {1..100}
do
	if ((a % 5 == 0 && a % 3 == 0))
	then
		echo "FizzBuzz"
	elif ((a % 3 == 0))
	then
		echo "Fizz"
	elif ((a % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$a"
	fi
done
