#!/usr/bin/env bash
#scipt to display Holberton School 10 times but good/bad luck int 4th and 8th

a="0"
while [ $a -lt 10 ]
do
	((a++))
	if [ $a -eq 4 ]
	then
		echo "bad luck"
	elif [ $a -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
done