#!/usr/bin/env bash
# To run nginx as nginx user

pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/sites-available/default
chmod 700 /etc/nginx/nginx.conf
chmod 700 /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart